name: Book desk.ly seat

on:
  schedule:
    # Runs at 9:00 AM UTC every weekday (Monday to Friday)
    - cron: '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  BookSeat:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version you need

    - name: Install dependencies
      run: make install

    - name: Book seat
      run: make run
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        SEAT_UUID: ${{ secrets.SEAT_UUID }}
        DAYS_UNTIL_BOOKING: ${{ secrets.DAYS_UNTIL_BOOKING }}
